apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "chart.labels" . | indent 6 }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "chart.labels" . | indent 8 }}
    spec:
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      containers:
        - name: price-oracle-server
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
{{- include "ports.pod" . | indent 8 }}
          env:
            - name: EMERIS-PRICE-ORACLE_DATABASECONNECTIONURL
              value: "{{ .Values.databaseConnectionURL }}"
            - name: EMERIS-PRICE-ORACLE_LISTENADDR
              value: 0.0.0.0:{{ .Values.ports.http }}
            - name: EMERIS-PRICE-ORACLE_DEBUG
              value: "{{ .Values.debug }}"
            - name: EMERIS-PRICE-ORACLE_LOGPATH
              value: ""
            - name: EMERIS-PRICE-ORACLE_INTERVAL
              value: "{{ .Values.interval }}"
            - name: EMERIS-PRICE-ORACLE_WHITELISTEDFIATS
              value: "EUR,USD"
            - name: EMERIS-PRICE-ORACLE_MAXASSETSREQ
              value: "{{ .Values.maxAssetsReq }}"
            {{- if .Values.fixerKey }}
            - name: EMERIS-PRICE-ORACLE_FIXERAPIKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: fixerKey
            {{- end }}
            - name: EMERIS-PRICE-ORACLE_RECOVERCOUNT
              value: "{{ .Values.recoverCount }}"
            - name: EMERIS-PRICE-ORACLE_WORKERPULSE
              value: "{{ .Values.workerPulse }}"
            - name: EMERIS-PRICE-ORACLE_HTTPCLIENTTIMEOUT
              value: "{{ .Values.httpClientTimeout }}"

          resources:
{{ toYaml .Values.resources | indent 12 }}
      terminationGracePeriodSeconds: 10