image: emeris/price-oracle-server:latest
imagePullPolicy: Always

replicas: 3

nodeSelector: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi

ports:
  http: 8000

databaseConnectionURL: postgres://root@cockroachdb:26257?sslmode=disable

debug: true

updateInterval: 20s

deamonPulse: 3s
