image: emeris/price-oracle-server:latest
imagePullPolicy: Always

replicas: 3

nodeSelector: {}

resources:
  requests:
    cpu: 100m
    memory: 1Gi
  limits:
    cpu: 100m
    memory: 4Gi


databaseConnectionURL: postgres://root@cockroachdb:26257?sslmode=disable

priceOracle:
  # no value means sentry is disabled
  sentryDSN:
  sentryEnvironment: local
  sentrySampleRate: 1.0
  sentryTracesSampleRate: 0.3

ports:
  http: 8000

debug: true

interval: 20s

maxAssetsReq: 10

recoverCount: 5

workerPulse: 3s

httpClientTimeout: 20s
