image: emeris/price-oracle-server:latest
imagePullPolicy: Always

replicas: 3

nodeSelector: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi


databaseConnectionURL: postgres://root@cockroachdb:26257?sslmode=disable

ports:
  http: 8000

debug: true

interval: 20s

maxAssetsReq: 10

recoverCount: 5

workerPulse: 3s

httpClientTimeout: 20s
