name: CI Unit test

on:
  push:
    branches:
      - main
      - develop
      - setup-ci
    paths-ignore:
      - "*.md"
      - "Dockerfile"
  pull_request:
    paths-ignore:
      - "*.md"
      - "Dockerfile"

jobs:
  test:
    name: Run Unit Test
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [self-hosted]
    runs-on: ${{ matrix.os }}

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup token for pulling from allinbits private repos
        run: |
          go env -w GOPRIVATE=github.com/allinbits/*
          git config --global url."https://git:${{ secrets.TENDERBOT_GIT_TOKEN }}@github.com".insteadOf "https://github.com"

      - name: Setup token for pulling from allinbits private repos
        run: |
          go env -w GOPRIVATE=github.com/allinbits/*
          git config --global url."https://git:${{ secrets.TENDERBOT_GIT_TOKEN }}@github.com".insteadOf "https://github.com"

      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - name: Go Build Cache
        uses: actions/cache@v3.0.3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      - name: Go Mod Cache
        uses: actions/cache@v3.0.3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Unit Test
        run: go test ./...
#
#      - name: Coverage
#        uses: codecov/codecov-action@v2.1.0
