name: CI

on:
  push:
    branches:
      - main
      - develop
      - setup-ci
    paths-ignore:
      - "*.md"
      - "Dockerfile"
  pull_request:
    paths-ignore:
      - "*.md"
      - "Dockerfile"

env:
  GO111MODULE: on
  GOPRIVATE: "github.com/allinbits/*"
  GOFLAGS: -mod=readonly
  TOKEN: ${{ secrets.TENDERBOT_GIT_TOKEN }}
  run: git config --global url."https://git:${TOKEN}@github.com".insteadOf "https://github.com"

jobs:
  test:
    name: Run Unit Test
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          # Required: the version of golangci-lint is required and must be
          # specified without patch version: we always use the latest patch version.
          version: v1.33

      - name: Unit Test
        run: go test -covermode=count -coverprofile=coverage.txt -count=1 ./...

      - name: Coverage
        uses: codecov/codecov-action@v2.1.0

#   lint:
#     name: Lint
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
      
#       - name: Setup Go
#         uses: actions/setup-go@v2
#         with:
#           go-version: 1.16.x
      
#       - name: golangci-lint
#         uses: golangci/golangci-lint-action@v2.5.2
#         with:
#           # Required: the version of golangci-lint is required and must be
#           # specified without patch version: we always use the latest patch version.
#           version: v1.33
