name: Deploy on Emeris Staging Environment

on:
  workflow_dispatch:
    inputs:
      version:
        description: Branch, tag or commit to deploy
        required: true
        default: master

jobs:
  price-oracle:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: '${{ secrets.KUBECONFIG_STAGING }}'
          exec: |
            helm upgrade price-oracle \
              --install \
              --namespace emeris \
              --set image=gcr.io/tendermint-dev/emeris-price-oracle:${{ github.event.inputs.version }} \
              --set fixerKey=${{ secrets.FIXER_KEY }} \
              --set replicas=3 \
              ./helm/emeris-price-oracle-server
