name: Build docker images

on:
  workflow_dispatch:
  workflow_run:
    workflows: [CI Unit test]
    branches: [main]
    types: [completed]

jobs:
  price-oracle-server:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: gcr.io/tendermint-dev/emeris-price-oracle:${{ steps.get_version.outputs.version-without-v }},gcr.io/tendermint-dev/emeris-price-oracle:${{ github.sha }}
          build-args: |
            GIT_TOKEN=${{ secrets.TENDERBOT_GIT_TOKEN }}

  deploy-on-dev:
    runs-on: self-hosted
    needs: price-oracle-server

    steps:
      - name: Call repository_dispatch on demeris-backend
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TENDERBOT_GIT_TOKEN }}
          repository: allinbits/demeris-backend
          event-type: dev-push-price-oracle-server
          client-payload: |
            {
              "repo_name":"emeris-price-oracle",
              "branch_name":"main",
              "image_name":"emeris-price-oracle",
              "image_sha":"${{ github.sha }}",
              "service_name":"price-oracle",
              "deploy_type":"deploy_dev"
            }
