name: Build docker images

on:
  workflow_dispatch:
  workflow_run:
    workflows: [CI Unit test]
    branches: [main]
    types: [completed]

jobs:
  docker-build-push: # NOT pushing to gcr now.
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: false  # TODO: Push to gcr when migration is done
          context: .
          file: Dockerfile
          tags: gcr.io/tendermint-dev/emeris-price-oracle:${{ steps.get_version.outputs.version-without-v }},gcr.io/tendermint-dev/emeris-price-oracle:${{ github.sha }}
          build-args: |
            GIT_TOKEN=${{ secrets.TENDERBOT_GIT_TOKEN }}
